"""Generate the identity-derivation parity fixture the Rust core is tested against.

Python is the source of truth for identity (implementation spec §2.2): the
engine must reproduce `tgms.core.model`'s canonical JSON, eid, and vid
byte-for-byte, or replayed stores would diverge from the frozen digests.
Rather than reimplement the rules twice and hope, we emit vectors from the
real Python functions and assert against them in `cargo test`.

Run via `make derive-vectors` after any change to canonical_json/edge_eid/_vid
(there should never be one — the formulas are frozen by D-001 and D-023).
"""

from __future__ import annotations

import json
from pathlib import Path

from tgms.core.model import canonical_json, edge_eid, sha256_hex

OUT = Path(__file__).resolve().parents[1] / (
    "crates/tgms-engine-core/tests/fixtures/derive_vectors.json"
)

# Strings chosen to exercise every branch of Python's json string encoder
# under ensure_ascii=False, plus the shapes real loaders actually produce.
STRINGS = [
    "",
    "a",
    "n1",
    "n1899",
    "SENT_MSG_TO",
    "RATED",
    "#0",
    "#49999",
    "Node",
    'quote"inside',
    "back\\slash",
    'both"\\mixed',
    "new\nline",
    "tab\there",
    "carriage\rreturn",
    "back\bspace",
    "form\ffeed",
    "nul\x00byte",
    "unit\x1fseparator",
    "bell\x07char",
    "slash/not/escaped",
    "delete\x7fchar",
    "café",
    "naïve résumé",
    "中文字符",
    "日本語のテキスト",
    "emoji 🎯 here",
    "combining é vs é",
    "line separator",
    "paragraph separator",
    "mixed 中文 \"quoted\" \\ and \n newline",
    "   leading and trailing   ",
    "a" * 300,
]

# (src, dst, rel_type, disc) tuples -> eid
EDGE_CASES = [
    ("n1", "n2", "SENT_MSG_TO", ""),
    ("n1", "n2", "SENT_MSG_TO", "#0"),
    ("n1", "n2", "SENT_MSG_TO", "#123456"),
    ("n2", "n1", "SENT_MSG_TO", "#0"),  # direction matters
    ("n1", "n1", "SENT_MSG_TO", "#7"),  # self-loop
    ("n5881", "n17", "RATED", "#35591"),
    ('quote"src', "back\\dst", "REL\nTYPE", "disc\ttab"),
    ("café", "中文", "EMOJI🎯REL", ""),
    ("", "", "", ""),  # degenerate but must still be defined
    ("a" * 200, "b" * 200, "LONG_REL", "#999"),
]

# (identity, tt_s, vt_s) -> vid.  identity is a uid for nodes, an eid for edges.
VID_CASES = [
    ("n1", 0, 0),
    ("n1", 1, 1),
    ("n42", 1_700_000_000_000_000, 1_082_040_961_000_000),
    ("0123456789abcdef01234567", 1_700_000_000_000_000, 0),
    ("0123456789abcdef01234567", 4_611_686_018_427_387_904, 4_611_686_018_427_387_903),
    ("café", 12345, 67890),
    ("", 0, 0),
    ("n1", -1, -1),  # negative timestamps are representable; str() must agree
    ("n1", 4_611_686_018_427_387_904, 0),  # OPEN_END as tt_s
]


def main() -> None:
    vectors = {
        "_comment": (
            "Generated by scripts/gen_derive_vectors.py from tgms.core.model. "
            "Python is the source of truth; the Rust core must match byte-for-byte."
        ),
        "canonical_json_string_arrays": [
            {"input": [s], "output": canonical_json([s])} for s in STRINGS
        ]
        + [
            {"input": list(t), "output": canonical_json(list(t))}
            for t in (EDGE_CASES[0], EDGE_CASES[6], EDGE_CASES[7])
        ],
        "sha256_hex": [{"input": s, "output": sha256_hex(s)} for s in STRINGS],
        "eid": [
            {
                "src": src,
                "dst": dst,
                "rel_type": rel,
                "disc": disc,
                "canonical": canonical_json([src, dst, rel, disc]),
                "eid": edge_eid(src, dst, rel, disc),
            }
            for src, dst, rel, disc in EDGE_CASES
        ],
        "vid": [
            {
                "identity": ident,
                "tt_s": tt_s,
                "vt_s": vt_s,
                # mirrors tgms.storage.base._vid exactly (D-001 refinement)
                "vid": sha256_hex(f"{ident}:{tt_s}:{vt_s}")[:24],
            }
            for ident, tt_s, vt_s in VID_CASES
        ],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(vectors, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    n = sum(len(v) for k, v in vectors.items() if isinstance(v, list))
    print(f"wrote {n} vectors to {OUT.relative_to(Path.cwd())}")


if __name__ == "__main__":
    main()
