#!/usr/bin/env python
"""Emit fig-bird-funnel.tex from the BIRD agent-arm receipt.

The certification funnel over the frozen 500-question universe:
universe -> executable SQL -> typed claim constructed -> certified ->
certified and correct, with each stage's exit reason annotated on the
drop. Fully generated from benchmarks/results-v1/eval-bird-agent.json;
re-running regenerates byte-for-byte.

    python scripts/paper_bird_funnel.py --outdir paper/ecqr
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REC = Path("benchmarks/results-v1/eval-bird-agent.json")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", type=Path, required=True)
    args = ap.parse_args()

    r = json.loads(REC.read_text())
    fu = r["funnel"]
    stages = [
        ("Frozen universe", fu["universe"], None),
        ("Executable SQL", fu["executable_sql"],
         f"no executable SQL after {r['freeze']['repair_rounds']} "
         f"repairs: {fu['universe'] - fu['executable_sql']}"),
        ("Typed claim constructed", fu["claim_constructed"],
         "shape mismatch with predeclared form: "
         f"{fu['executable_sql'] - fu['claim_constructed']}"),
        ("Certified", fu["certified"],
         "verifier withheld: "
         f"{fu['claim_constructed'] - fu['certified']}"),
        ("Certified and correct", fu["certified_and_correct"],
         "certified but wrong vs.\\ gold: "
         f"{fu['certified'] - fu['certified_and_correct']}"),
    ]
    names = [s[0] for s in stages]
    ycoords = ",".join(reversed(names))
    bars = " ".join(f"({v},{n})" for n, v, _ in stages)
    drops = []
    for i, (name, _v, note) in enumerate(stages):
        if note is None:
            continue
        prev_v = stages[i - 1][1]
        drops.append(
            rf"\node[anchor=west, font=\tiny, text=black!60] at "
            rf"(axis cs:{prev_v},{{{name}}}) {{$\leftarrow$ {note}}};")
    tex = "\n".join([
        "% GENERATED by scripts/paper_bird_funnel.py -- do not edit.",
        "% Source: benchmarks/results-v1/eval-bird-agent.json.",
        r"\begin{figure}[t]",
        r"\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[xbar, width=0.94\linewidth, height=3.9cm,",
        rf"  symbolic y coords={{{ycoords}}}, ytick=data,",
        r"  xmin=0, xmax=" + str(int(fu["universe"] * 1.55)) + ",",
        r"  y tick label style={font=\scriptsize},",
        r"  x tick label style={font=\tiny},",
        r"  bar width=7pt, nodes near coords,",
        r"  every node near coord/.append style={font=\tiny},",
        r"  axis x line*=bottom, axis y line*=left]",
        rf"\addplot+[fill=black!25, draw=black!70] coordinates "
        rf"{{{bars}}};",
        *drops,
        r"\end{axis}",
        r"\end{tikzpicture}",
        r"\caption{The certification funnel on BIRD Mini-Dev "
        r"(frozen 500-question universe, single frozen configuration). "
        r"Each drop is an exit the contract makes explicit: the agent "
        r"produced no executable SQL, its result shape did not match "
        r"the predeclared claim form, the verifier withheld the claim, "
        r"or a certified claim disagreed with the re-executed gold "
        r"result.}",
        r"\label{fig:birdfunnel}",
        r"\end{figure}",
        ""])
    out = args.outdir / "fig-bird-funnel.tex"
    out.write_text(tex)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
