#!/usr/bin/env python
"""Emit tab-fault-families.tex: EvidenceBench collapsed to fault families.

The full 27-cell decision matrix is hard to read at print size, so the
main paper carries a family-level summary of where each checker errs
and the per-cell matrix ships with the artifact. Errors are counted
against the declared expectation: a fault cell that certifies is a
false accept, a control cell that does not certify is a false reject.

    python scripts/paper_fault_families.py --outdir paper/ecqr
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REC = Path("benchmarks/results-v1/eval-fault-matrix.json")
BASE = Path("benchmarks/results-v1/eval-baseline-checkers.json")

FAMILY = {
    "clean": "controls (must certify)",
    "page_truncation": "delivery incompleteness",
    "execution_incomplete": "execution incompleteness",
    "wrong_count": "value / witness",
    "wrong_scalar": "value / witness",
    "uncited_value": "value / witness",
    "omitted_member": "value / witness",
    "fabricated_member": "value / witness",
    "false_membership": "value / witness",
    "false_existence": "value / witness",
    "false_nonexistence": "value / witness",
    "wrong_snapshot": "basis",
    "unpinned_snapshot": "basis",
    "digest_mismatch": "integrity",
}
ORDER = ["controls (must certify)", "delivery incompleteness",
         "execution incompleteness", "value / witness", "basis",
         "integrity"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", type=Path, required=True)
    args = ap.parse_args()
    fm = json.loads(REC.read_text())
    cells = fm["cells"]
    assert set(c["fault"] for c in cells) <= set(FAMILY), "unmapped fault"

    bc = json.loads(BASE.read_text())

    def errs(key):
        """cell ids where this checker disagreed with the expectation"""
        d = bc[key]
        return set(d.get("fc_cells", [])) | set(d.get("fr_cells", []))

    b1, b2 = errs("b1_value_only"), errs("b2_taint_all")
    rows = []
    for fam in ORDER:
        sub = [c for c in cells if FAMILY[c["fault"]] == fam]
        if not sub:
            continue
        ids = {f"{c['claim']}/{c['fault']}" for c in sub}
        rows.append((fam, len(sub), len(ids & b1), len(ids & b2),
                     sum(1 for c in sub if not c["ok"])))
    tex = "\n".join([
        "% GENERATED by scripts/paper_fault_families.py -- do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{EvidenceBench by fault family: decision errors for",
        r"the two simple checkers of \S\ref{sec:naive} and for the ECQR",
        r"verifier. Errors are counted",
        r"against the declared expectation: a fault cell that certifies",
        r"is a false accept, a control cell that does not is a false",
        r"reject. The per-cell decisions for all three checkers ship",
        r"with the artifact.}",
        r"\label{tab:faultfam}",
        r"\small",
        r"\begin{tabular}{@{}lrrrr@{}}",
        r"\toprule",
        r"Fault family & cells & value-only & taint & ECQR \\",
        r"\midrule",
    ] + [rf"{f} & {n} & {a} & {b} & {e} \\" for f, n, a, b, e in rows] + [
        r"\midrule",
        rf"\textbf{{All}} & \textbf{{{len(cells)}}} & "
        rf"\textbf{{{sum(r[2] for r in rows)}}} & "
        rf"\textbf{{{sum(r[3] for r in rows)}}} & "
        rf"\textbf{{{sum(r[4] for r in rows)}}} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        ""])
    out = args.outdir / "tab-fault-families.tex"
    out.write_text(tex)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
