#!/usr/bin/env python
"""Emit tab-bird-census.tex: BIRD contract coverage by question intent.

Question-level table only: for each natural-language intent contract,
how many questions, how many have any supported typed claim, and how
many meet the stricter full-contract criterion. The instantiated-claim
breakdown (Scalar/CompleteSet/ExactCount counts) is carried in prose,
not in this table.

    python scripts/paper_bird_census.py --outdir paper/ecqr
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REC = Path("benchmarks/results-v1/eval-bird-agent.json")
LABEL = {"SCALAR": "Scalar", "SCALAR_TUPLE": "Scalar tuple",
         "COMPLETE_SET": "Complete collection", "EXISTS": "Existence",
         "SET_AND_COUNT": "Multipart (collection + count)",
         "OUTSIDE_FRAGMENT": "Outside the fragment"}
ORDER = ["SCALAR", "SCALAR_TUPLE", "COMPLETE_SET", "EXISTS",
         "SET_AND_COUNT", "OUTSIDE_FRAGMENT"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", type=Path, required=True)
    args = ap.parse_args()
    r = json.loads(REC.read_text())
    bf = r["by_form"]
    qrows = [(LABEL[k], bf[k]["n"], bf[k]["certified"],
              bf[k].get("certified_full_contract", 0))
             for k in ORDER if k in bf]
    assert sum(x[1] for x in qrows) == r["n"], "questions must sum to n"
    tex = "\n".join([
        "% GENERATED by scripts/paper_bird_census.py -- do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{BIRD contract coverage by question intent.",
        r"\emph{Any cert.} requires at least one supported typed",
        r"claim; \emph{strict full} requires the complete result",
        r"contract under the conservative multiplicity/order policy.}",
        r"\label{tab:birdcensus}",
        r"\small",
        r"\begin{tabular}{@{}lrrr@{}}",
        r"\toprule",
        r"Intent contract & Questions & Any cert. & Strict full \\",
        r"\midrule",
    ])
    body = [f"{lab} & {n} & {cert} & {full} \\\\"
            for lab, n, cert, full in qrows]
    tex += "\n" + "\n".join(body) + "\n" + "\n".join([
        r"\midrule",
        rf"\textbf{{All}} & \textbf{{{r['n']}}} & "
        rf"\textbf{{{r['certified']}}} & "
        rf"\textbf{{{r['certified_full_contract']}}} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        ""])
    out = args.outdir / "tab-bird-census.tex"
    out.write_text(tex)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
