#!/usr/bin/env python
"""Emit tab-ldbc-coverage.tex from the frozen LDBC coverage annotation.

Fully generated float, no hand transcription: reads
external_workloads/ldbc/coverage_annotation.jsonl and the receipt
benchmarks/results-v1/eval-ldbc-coverage.json, writes one booktabs
table with the two frozen dimensions (execution coverage against the
15-operator surface; claim coverage against the FULL result contract)
plus the set-projection column.

    python scripts/paper_ldbc_table.py --outdir paper/ecqr
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ANN = Path("external_workloads/ldbc/coverage_annotation.jsonl")
REC = Path("benchmarks/results-v1/eval-ldbc-coverage.json")

GROUPS = [("IC1--14", "IC"), ("IS1--7", "IS"), ("BI1--20", "BI")]
EXEC_COLS = ["DIRECT_TGMS", "DECOMPOSABLE_TGMS", "SQL_ONLY",
             "UNSUPPORTED_EXECUTION"]
CLAIM_COLS = ["CURRENT_ECQR_FRAGMENT", "REQUIRES_ORDERED_RESULT",
              "REQUIRES_TOP_K", "REQUIRES_GROUPWISE_EXTREMUM",
              "REQUIRES_PATH_CERTIFICATE"]


def counts(rows, prefix, key, values):
    sub = [r for r in rows if r["query_id"].startswith(prefix)]
    return [sum(1 for r in sub if r[key] == v) for v in values]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", type=Path, required=True)
    args = ap.parse_args()

    rows = [json.loads(l) for l in open(ANN)]
    rec = json.loads(REC.read_text())
    assert len(rows) == rec["n_templates"] == 41

    def line(label, prefix):
        if prefix:
            sub = [r for r in rows if r["query_id"].startswith(prefix)]
        else:
            sub = rows
        ex = [sum(1 for r in sub if r["exec_coverage"] == v)
              for v in EXEC_COLS]
        cl = [sum(1 for r in sub if r["claim_full_contract"] == v)
              for v in CLAIM_COLS]
        sp = sum(1 for r in sub if r["flat_projection_in_fragment"])
        cells = [label] + [str(v) for v in ex + cl] + [
            f"{sp}/{len(sub)}"]
        return " & ".join(cells) + r" \\"

    # IS rows never start with "IC" etc. -- prefixes are disjoint by
    # construction (IC, IS, BI)
    body = [line(lab, pre) for lab, pre in GROUPS]
    total = line(r"\textbf{All 41}", None)

    tex = "\n".join([
        "% GENERATED by scripts/paper_ldbc_table.py -- do not edit.",
        "% Source: external_workloads/ldbc/coverage_annotation.jsonl,",
        "% receipt benchmarks/results-v1/eval-ldbc-coverage.json.",
        r"\begin{table}[t]",
        r"\centering",
        rf"\caption{{LDBC coverage over all {rec['n_templates']} SNB",
        r"read templates. Execution columns are Direct,",
        r"Decomposable, SQL-only, and Unsupported. Claim columns",
        r"partition templates by the first full-contract feature the",
        r"current grammar lacks: \emph{Frag.} counts templates",
        r"already inside the fragment, followed by Ordered result,",
        r"Top-$k$, Groupwise extremum, and Path. \emph{Flat proj.}",
        r"reports duplicate-insensitive unordered flat-tuple",
        r"projection coverage.}",
        r"\label{tab:ldbc}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{2.6pt}",
        r"\begin{tabular}{@{}l cccc ccccc c@{}}",
        r"\toprule",
        r" & \multicolumn{4}{c}{Execution coverage}"
        r" & \multicolumn{5}{c}{Claim coverage (full contract)}"
        r" & Flat \\",
        r"\cmidrule(lr){2-5}\cmidrule(lr){6-10}",
        r"Template group & Dir. & Dec. & SQL & Uns."
        r" & Frag. & Ord. & Top-$k$ & G-ext & Path & proj. \\",
        r"\midrule",
        *body,
        r"\midrule",
        total,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        ""])
    out = args.outdir / "tab-ldbc-coverage.tex"
    out.write_text(tex)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
