#!/usr/bin/env python
"""Emit fig-bird-funnel.tex from the BIRD agent-arm receipt.

One two-column figure. Left: the certification funnel over the frozen
500-question universe (universe -> executable SQL -> typed claim
constructed -> certified -> strict full contract), with each stage's
exit reason annotated on the drop, and beneath it the 2x2 matrix of
any-claim certification against gold agreement. Right: the census of
questions per intent contract split by certification outcome (former
fig-bird-census, built by paper_figures.bird_census_panel; that file is
now an empty stub). Fully generated from
benchmarks/results-v1/eval-bird-agent.json; re-running regenerates
byte-for-byte.

    python scripts/paper_bird_funnel.py --outdir paper/ecqr
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REC = Path("benchmarks/results-v1/eval-bird-agent.json")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", type=Path, required=True)
    args = ap.parse_args()

    # shared figure helpers (palette-only styling, macro checks)
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from paper_figures import (DL, SQ, bird_census_panel, check_macro,
                               load_macros)
    mac = load_macros(args.outdir / "pn-macros.tex")

    r = json.loads(REC.read_text())
    fu = r["funnel"]
    stages = [
        ("universe", fu["universe"], None),
        ("executable SQL", fu["executable_sql"],
         f"$-{fu['universe'] - fu['executable_sql']}$ no SQL"),
        ("typed claim", fu["claim_constructed"],
         f"$-{r['stage_counts'].get('shape_mismatch', 0)}$ shape, "
         f"$-{r.get('outside_fragment', 0)}$ outside"),
        ("any claim certified", fu["certified"],
         f"$-{fu['claim_constructed'] - fu['certified']}$ withheld"),
        ("strict full contract", r["certified_full_contract"],
         f"$-{r['certified_partial_contract']}$ partial"),
    ]
    # support x gold agreement: the paper's central boundary in four cells
    cc = fu["certified_and_correct"]
    cw = fu["certified"] - cc
    nc_right = r["em_overall"] - cc
    nc_wrong = fu["universe"] - fu["certified"] - nc_right
    for name, val in [("pnBirdN", fu["universe"]),
                      ("pnBirdExec", fu["executable_sql"]),
                      ("pnBirdClaim", fu["claim_constructed"]),
                      ("pnBirdCert", fu["certified"]),
                      ("pnBirdCertFull", r["certified_full_contract"]),
                      ("pnBirdCertPartial", r["certified_partial_contract"]),
                      ("pnBirdShapeMismatch", r["stage_counts"]["shape_mismatch"]),
                      ("pnBirdOutside", r["outside_fragment"]),
                      ("pnBirdCertCorrect", cc), ("pnBirdCertWrong", cw),
                      ("pnBirdUncertEm", nc_right),
                      ("pnBirdNoClaimWrong", nc_wrong),
                      ("pnBirdGoldFull", r["gold_match_full_contract"])]:
        check_macro(mac, name, val)

    ys = list(range(len(stages)))[::-1]
    ytl = ",".join(f"{{{s[0]}}}" for s in stages)
    bars = " ".join(f"({v},{y})" for (_n, v, _), y in zip(stages, ys))
    inside, after = [], []
    for i, ((_n, v, note), y) in enumerate(zip(stages, ys)):
        inside.append(rf"\coordinate (f{i}) at (axis cs:{v},{y});")
        after.append(rf"\node[{DL}, anchor=east, xshift=-1pt] at (f{i}) "
                     rf"{{{v}}};")
        if note:
            after.append(rf"\node[{DL}, anchor=west, xshift=2pt, "
                         rf"text=figMid] at (f{i}) {{{note}}};")
    # 2x2 matrix below the funnel, column/row heads in picture text size
    w, h = 1.55, 0.55
    cells = [(0, 1, cc, "figLight"), (1, 1, cw, "figAccentLight"),
             (0, 0, nc_right, "figLight!40"), (1, 0, nc_wrong, "figLight!40")]
    matrix = []
    for x, y, v, fill in cells:
        matrix.append(
            rf"\fill[{fill}] ({x * w:.2f},{y * h:.2f}) rectangle "
            rf"({x * w + w - 0.04:.2f},{y * h + h - 0.04:.2f});")
        matrix.append(
            rf"\node at ({x * w + (w - 0.04) / 2:.3f},"
            rf"{y * h + (h - 0.04) / 2:.3f}) {{{v}}};")
    # census on the right: its plot box top sits one legend row below
    # the funnel's first bar so the legend lines up with the funnel top
    cen_axis, cen_after = bird_census_panel(
        r, mac, r"at={($(fun.north east)+(3.3cm,-0.55cm)$)}, "
        r"anchor=north west, scale only axis, width=0.25\textwidth, ")
    tex = "\n".join([
        "% GENERATED by scripts/paper_bird_funnel.py -- do not edit.",
        "% Source: benchmarks/results-v1/eval-bird-agent.json (funnel,",
        "% stage_counts, by_form).",
        r"\begin{figure*}[t]",
        r"\centering",
        r"\begin{tikzpicture}",
        rf"\begin{{axis}}[name=fun, xbar, {SQ}, scale only axis,",
        r"  width=0.32\textwidth,",
        r"  y=0.42cm, bar width=7pt, xmin=0, xmax=820, clip=false,",
        rf"  ytick={{{','.join(map(str, ys))}}}, yticklabels={{{ytl}}},",
        rf"  ymin=-0.6, ymax={len(stages) - 0.4}, y tick style={{draw=none}},",
        r"  axis x line=none, axis y line*=left]",
        rf"\addplot[fill=figLight, draw=none] coordinates {{{bars}}};",
        *inside,
        r"\end{axis}",
        *after,
        r"\begin{scope}[shift={($(fun.south west)+(1.9cm,-1.6cm)$)}]",
        *matrix,
        rf"\node[anchor=south] at ({w / 2 - 0.02:.2f},{2 * h:.2f}) "
        r"{gold match};",
        rf"\node[anchor=south] at ({w * 1.5 - 0.02:.2f},{2 * h:.2f}) "
        r"{gold mismatch};",
        rf"\node[anchor=east] at (-0.08,{h * 1.5 - 0.02:.2f}) "
        r"{certified};",
        rf"\node[anchor=east] at (-0.08,{h / 2 - 0.02:.2f}) "
        r"{no certified claim};",
        r"\end{scope}",
        cen_axis.rstrip("\n"),
        cen_after,
        r"\end{tikzpicture}",
        r"\caption{BIRD Mini-Dev. \emph{Top left}: certification funnel "
        r"over the \pnBirdN\ questions, with the reason for each drop. "
        r"\emph{Bottom left}: any-claim certification against "
        r"published-gold agreement. \emph{Right}: questions by intent "
        r"contract, split by certification outcome; numbers at the bar "
        r"ends give the questions that meet the strict full contract over "
        r"all questions of that contract. Certification does not imply "
        r"gold agreement: \pnBirdCertCorrect\ of the \pnBirdCert\ "
        r"certified runs match gold, and \pnBirdGoldFull\ of those also "
        r"meet the strict full contract. The \pnBirdCertPartial\ runs "
        r"between any-claim and strict-full certification all lie in the "
        r"complete-collection row.}",
        r"\label{fig:birdfunnel}",
        r"\label{fig:birdcensus}",
        r"\end{figure*}",
        ""])
    out = args.outdir / "fig-bird-funnel.tex"
    out.write_text(tex)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
