#!/usr/bin/env python
"""Emit tab-bird-census.tex: the two-level BIRD contract census.

The units differ deliberately and the table says so: the left block
counts QUESTIONS by the contract their natural-language intent
requests, the right block counts the typed ECQR CLAIMS those
questions instantiate. A one-row k-column answer is one question and
k Scalar claims; the single multipart item is one question and two
claims.

    python scripts/paper_bird_census.py --outdir paper/ecqr
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REC = Path("benchmarks/results-v1/eval-bird-agent.json")
LABEL = {"SCALAR": "Scalar", "SCALAR_TUPLE": "Scalar tuple",
         "COMPLETE_SET": "Complete collection", "EXISTS": "Existence",
         "SET_AND_COUNT": "Multipart (collection + count)",
         "OUTSIDE_FRAGMENT": "Outside the fragment"}
ORDER = ["SCALAR", "SCALAR_TUPLE", "COMPLETE_SET", "EXISTS",
         "SET_AND_COUNT", "OUTSIDE_FRAGMENT"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", type=Path, required=True)
    args = ap.parse_args()
    r = json.loads(REC.read_text())
    bf, cc = r["by_form"], r["claim_kind_census"]
    full = json.loads(Path("external_workloads/bird/agent_run/"
                           "receipt.json").read_text()) if False else None
    qrows = [(LABEL[k], bf[k]["n"], bf[k]["certified"],
              bf[k].get("certified_full_contract", 0))
             for k in ORDER if k in bf]
    assert sum(x[1] for x in qrows) == r["n"], "questions must sum to n"
    crows = [("\\textsf{Scalar}", cc["scalar"]),
             ("\\textsf{CompleteSet}", cc["complete_set"]),
             ("\\textsf{ExactCount}", cc["exact_count"])]
    tex = "\n".join([
        "% GENERATED by scripts/paper_bird_census.py -- do not edit.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{What BIRD asks of the claim grammar. \emph{Left}:",
        r"questions by the contract their natural-language intent",
        r"requests. \emph{Right}: the typed claims those questions",
        r"instantiate. The units differ --- a one-row $k$-column answer",
        r"is one question and $k$ \textsf{Scalar} claims --- so the two",
        r"blocks are not expected to agree. \emph{any cert.} counts",
        r"questions with at least one supported typed claim;",
        r"\emph{full} counts those whose entire adjudicated contract is",
        r"represented and supported.}",
        r"\label{tab:birdcensus}",
        r"\small",
        r"\begin{tabular}{@{}lrrr@{\hspace{1.2em}}lr@{}}",
        r"\toprule",
        r"Intent contract & Qs & any cert. & full & Claim form"
        r" & Claims \\",
        r"\midrule",
    ])
    body = []
    for i in range(max(len(qrows), len(crows))):
        left = (f"{qrows[i][0]} & {qrows[i][1]} & {qrows[i][2]}"
                f" & {qrows[i][3]}"
                if i < len(qrows) else " & & & ")
        right = (f"{crows[i][0]} & {crows[i][1]}"
                 if i < len(crows) else " & ")
        body.append(f"{left} & {right} \\\\")
    tex += "\n" + "\n".join(body) + "\n" + "\n".join([
        r"\midrule",
        rf"\textbf{{All}} & \textbf{{{r['n']}}} & "
        rf"\textbf{{{r['certified']}}} & "
        rf"\textbf{{{r['certified_full_contract']}}} & &"
        rf" \textbf{{{sum(c[1] for c in crows)}}} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        ""])
    out = args.outdir / "tab-bird-census.tex"
    out.write_text(tex)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
